service: my-finances-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:119135969665:table/FinancialMovements

functions:
  insertFinancialMovement:
    handler: src/insertFinancialMovement.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  getFinancialMovements:
    handler: src/getFinancialMovements.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  deleteFinancialMovement:
    handler: src/deleteFinancialMovement.handler
    events:
      - http:
          path: /deleteFinancialMovement
          method: delete
          cors: true
  updateFinancialMovement:
    handler: src/updateFinancialMovement.handler
    events:
      - http:
          path: /
          method: put
          cors: true

resources:
  Resources:
    MyFinancesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FinancialMovements
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: rangeId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: rangeId
            KeyType: RANGE
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId: 
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false




